[tool.pytest.ini_options]
addopts = "--verbose"
markers = ["application: application layer tests","domain: domain layer tests","infrastructure: infrastructure layer tests"]

[tool.taskipy.tasks]
test = "pytest tests/"
test-app = "pytest -m application tests/"
test-domain = "pytest -m domain tests/"
test-infra = "pytest -m infrastructure tests/"